log_dest stdout
allow_anonymous false
persistence true
persistence_location /mosquitto/data/
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json
per_listener_settings false

listener 1883
